# Generated by Django 3.0.8 on 2020-09-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rookieplays', '0008_auto_20200903_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='data/documents/'),
        ),
    ]
