# Generated by Django 3.0.8 on 2020-09-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rookieplays', '0009_auto_20200903_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
